package cmd

import (
	"fmt"
	"os"
	"strings"

	"github.com/leihog/shdw/internal/store"
	"github.com/spf13/cobra"
)

var exportOutput string
var exportPathPrefix bool

var exportCmd = &cobra.Command{
	Use:   "export <path> [path...]",
	Short: "Export secrets to .env format",
	Long: `Export secrets from one or more paths as KEY=VALUE lines.

Each path can be a namespace (exports all direct child keys) or a single key.
Multiple paths are merged in order — later paths override earlier ones on
env var name collision.

Output goes to stdout by default; use -o to write to a file.`,
	Example: `  shdw export discord
  shdw export discord discord/prod
  shdw export discord discord/prod -o .env
  shdw export discord/prod/token`,
	Args:              cobra.MinimumNArgs(1),
	ValidArgsFunction: anyCompleter,
	RunE: func(cmd *cobra.Command, args []string) error {
		password, err := getMasterPassword(false)
		if err != nil {
			return err
		}

		vault, err := store.Load(password)
		if err != nil {
			return err
		}

		secrets, err := vault.ResolveMany(args, exportPathPrefix)
		if err != nil {
			return err
		}
		if len(secrets) == 0 {
			fmt.Fprintln(os.Stderr, "No secrets found for the specified path(s).")
			return nil
		}

		out := os.Stdout
		if exportOutput != "" {
			f, err := os.Create(exportOutput)
			if err != nil {
				return err
			}
			defer f.Close()
			out = f
		}

		fmt.Fprintf(out, "# Generated by shdw — paths: %s\n", strings.Join(args, ", "))
		for _, s := range secrets {
			fmt.Fprintf(out, "%s=%s\n", s.EnvVarName(exportPathPrefix), s.Value)
		}

		if exportOutput != "" {
			fmt.Fprintf(os.Stderr, "Exported %d secrets to %s\n", len(secrets), exportOutput)
		}
		return nil
	},
}

func init() {
	exportCmd.Flags().StringVarP(&exportOutput, "output", "o", "", "Write to file instead of stdout")
	exportCmd.Flags().BoolVar(&exportPathPrefix, "add-path-prefix", false, "Prefix env var names with the full path (e.g. DISCORD_PROD_TOKEN)")
}
